from sqlalchemy import Column, Integer, String, Float, Date
from .database import Base

class ProjectExecution(Base):
    __tablename__ = "project_execution"

    id = Column(Integer, primary_key=True, index=True)
    bpin = Column(String, index=True)
    adiciones = Column(Float)
    anio = Column(Integer)
    aplazamiento = Column(Float)
    area_funcional = Column(String)
    bp = Column(String)
    centro_gestor = Column(String)
    clasificacion_fondo = Column(String)
    comuna = Column(String)
    contracreditos = Column(Float)
    creditos = Column(Float)
    dataframe_origen = Column(String)
    desaplazamiento = Column(Float)
    dimension = Column(String)
    ejecucion = Column(Float)
    fondo = Column(String)
    linea_estrategica = Column(String)
    nombre_actividad = Column(String)
    nombre_area_funcional = Column(String)
    nombre_centro_gestor = Column(String)
    nombre_dimension = Column(String)
    nombre_fondo = Column(String)
    nombre_linea_estrategica = Column(String)
    nombre_pospre = Column(String)
    nombre_programa = Column(String)
    nombre_proyecto = Column(String)
    organismo = Column(String)
    origen = Column(String)
    pagos = Column(Float)
    periodo = Column(Date)
    pospre = Column(String)
    ppto_disponible = Column(Float)
    ppto_inicial = Column(Float)
    ppto_modificado = Column(Float)
    programa_presupuestal = Column(String)
    reducciones = Column(Float)
    saldos_cdp = Column(Float)
    tipo_gasto = Column(String)
    total_acumul_obligac = Column(Float)
    total_acumulado_cdp = Column(Float)
    total_acumulado_rpc = Column(Float)
    vigencia = Column(Integer)
